services:
  - type: web
    name: FastAPI-ML-Project
    env: docker
    plan: free
    branch: main
    autoDeploy: true
    dockerfilePath: ./Dockerfile
    envVars:
      - key: MODEL_PATH
        value: app/models/model.joblib